name: ARM32 Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,ubuntu:latest'

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
        docker system prune -a -f
        docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        bash .github/scripts/package-images.sh \
          "linux/arm/v7" \
          "arm32" \
          "arm32-images.tar.gz" \
          "${{ github.event.inputs.docker_images }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: arm32-images.tar.gz
        retention-days: 1
